#!/bin/bash
set -euxo pipefail
exec > >(tee -a /var/log/userdata-kafka.log) 2>&1

log() { echo "[$(date -Is)] $*"; }
trap 'log "ERROR on line $LINENO"; exit 1' ERR

# -----------------------------------------------------------------------------
# IMDSv2: instance private IP (advertised for Kafka)
# -----------------------------------------------------------------------------
IMDS="http://169.254.169.254"
TOKEN=$(
  curl -sS -X PUT "${IMDS}/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || true
)
curl_hdr=()
if [[ -n "${TOKEN:-}" ]]; then
  curl_hdr=(-H "X-aws-ec2-metadata-token: $TOKEN")
fi
PRIVATE_IP=$(curl -sS "${curl_hdr[@]}" "${IMDS}/latest/meta-data/local-ipv4")
log "Private IP: $PRIVATE_IP"

# -----------------------------------------------------------------------------
# Java 17 (Amazon Corretto)
# -----------------------------------------------------------------------------
if ! command -v java >/dev/null 2>&1; then
  dnf install -y java-17-amazon-corretto java-17-amazon-corretto-devel
fi
java -version

# -----------------------------------------------------------------------------
# Apache Kafka 3.7.x (KRaft, no ZooKeeper)
# -----------------------------------------------------------------------------
KAFKA_VERSION="3.7.2"
KAFKA_TGZ="kafka_2.13-${KAFKA_VERSION}.tgz"
KAFKA_DIR="/opt/kafka"
KAFKA_LOG_DIR="/var/lib/kafka/kraft-combined-logs"

if [[ ! -d "$KAFKA_DIR/config" ]]; then
  mkdir -p /opt
  pushd /opt
  curl -fSL "https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/${KAFKA_TGZ}" -o "$KAFKA_TGZ"
  tar xzf "$KAFKA_TGZ"
  rm -f "$KAFKA_TGZ"
  KAFKA_EXTRACT="kafka_2.13-${KAFKA_VERSION}"
  rm -rf "$KAFKA_DIR"
  mv "/opt/${KAFKA_EXTRACT}" "$KAFKA_DIR"
  popd
fi
mkdir -p "$KAFKA_LOG_DIR" /etc/kafka
chown -R 1000:1000 "$KAFKA_LOG_DIR" 2>/dev/null || chown -R root:root "$KAFKA_LOG_DIR"

KAFKA_CFG="/etc/kafka/server-kraft.properties"
log "Writing $KAFKA_CFG"
cat >"$KAFKA_CFG" <<EOF
# KRaft single node — generated by userdata
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@${PRIVATE_IP}:9093
listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
inter.broker.listener.name=PLAINTEXT
advertised.listeners=PLAINTEXT://${PRIVATE_IP}:9092
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
controller.listener.names=CONTROLLER
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=${KAFKA_LOG_DIR}
num.partitions=1
default.replication.factor=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
EOF

KAFKA_BIN="$KAFKA_DIR/bin"
export CLUSTER_ID=$("$KAFKA_BIN/kafka-storage.sh" random-uuid)
log "Cluster id: $CLUSTER_ID"

# Format storage (idempotent check: if already formatted, format may error — use metadata check)
if [[ ! -f "$KAFKA_LOG_DIR/meta.properties" ]]; then
  "$KAFKA_BIN/kafka-storage.sh" format -t "$CLUSTER_ID" -c "$KAFKA_CFG" --ignore-formatted
else
  log "Kafka log directory already formatted; skipping format"
fi

# -----------------------------------------------------------------------------
# kafka systemd + JMX on 9999
# -----------------------------------------------------------------------------
cat >/etc/systemd/system/kafka.service <<'UNIT'
[Unit]
Description=Apache Kafka (KRaft)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Environment=LOG_DIR=/var/log/kafka
Environment=KAFKA_HEAP_OPTS=-Xmx512M -Xms512M
Environment=KAFKA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=PRIVATEIP_PLACEHOLDER
ExecStart=/opt/kafka/bin/kafka-server-start.sh /etc/kafka/server-kraft.properties
ExecStop=/opt/kafka/bin/kafka-server-stop.sh
Restart=on-failure
RestartSec=5
LimitNOFILE=100000
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
UNIT
sed -i "s/PRIVATEIP_PLACEHOLDER/${PRIVATE_IP}/g" /etc/systemd/system/kafka.service
mkdir -p /var/log/kafka

systemctl daemon-reload
systemctl enable --now kafka.service
log "Waiting for broker on 9092..."
for i in $(seq 1 60); do
  if "$KAFKA_BIN/kafka-broker-api-versions.sh" --bootstrap-server "localhost:9092" >/dev/null 2>&1; then
    log "Broker is up"
    break
  fi
  sleep 2
  if [[ "$i" -eq 60 ]]; then
    log "Timeout waiting for Kafka"
    systemctl --no-pager -l status kafka || true
    exit 1
  fi
done

for t in payments payments.dlq payments.audit; do
  "$KAFKA_BIN/kafka-topics.sh" --create --if-not-exists --bootstrap-server localhost:9092 \
    --topic "$t" --partitions 1 --replication-factor 1
  log "Topic $t created or exists"
done

# -----------------------------------------------------------------------------
# Python admin shim
# -----------------------------------------------------------------------------
dnf install -y python3-pip python3-devel gcc
pip3 install --no-cache-dir flask confluent-kafka

cat >/opt/kafka/kafka_admin.py <<'PY'
import os
import uuid
from time import time

from confluent_kafka import Consumer, TopicPartition, KafkaError
from confluent_kafka.admin import AdminClient
from flask import Flask, jsonify, request

app = Flask(__name__)
BOOT = os.environ.get("KAFKA_BOOTSTRAP", "localhost:9092")


def admin():
    return AdminClient({"bootstrap.servers": BOOT, "api.version.request": True})


@app.route("/health")
def health():
    return jsonify(status="ok", bootstrap=BOOT, ts=time()), 200


@app.route("/topics")
def list_topics():
    md = admin().list_topics(timeout=10)
    out = []
    c = Consumer(
        {
            "bootstrap.servers": BOOT,
            "group.id": f"admin-stats-{uuid.uuid4()}",
            "enable.auto.commit": False,
        }
    )
    try:
        for tname, t in md.topics.items():
            if tname.startswith("__"):
                continue
            parts = []
            total_msgs = 0
            for pid in t.partitions:
                tp = TopicPartition(tname, pid)
                try:
                    lo, hi = c.get_watermark_offsets(tp, 5)
                except Exception as exc:  # noqa: BLE001
                    parts.append({"partition": int(pid), "error": str(exc)})
                    continue
                total_msgs += max(0, hi - lo)
                parts.append({"partition": int(pid), "low": int(lo), "high": int(hi)})
            out.append(
                {
                    "name": tname,
                    "partitions": len(t.partitions),
                    "message_count_approx": total_msgs,
                    "partitions_detail": parts,
                }
            )
    finally:
        c.close()
    return jsonify(topics=sorted(out, key=lambda x: x["name"])), 200


@app.route("/topics/<name>/messages")
def sample_messages(name: str):
    limit = int(request.args.get("limit", 10) or 10)
    limit = max(1, min(limit, 500))
    md = admin().list_topics(timeout=5)
    if name not in md.topics:
        return jsonify(error=f"Unknown topic: {name}"), 404
    tmeta = md.topics[name]
    if not tmeta.partitions:
        return jsonify(error="No partitions for topic", topic=name), 400
    # Sample from the first partition (typical 1 partition in this demo)
    p0 = sorted(tmeta.partitions)[0]
    c = Consumer(
        {
            "bootstrap.servers": BOOT,
            "group.id": f"admin-read-{uuid.uuid4()}",
            "enable.auto.commit": False,
        }
    )
    collected = []
    try:
        tp0 = TopicPartition(name, p0)
        lo, hi = c.get_watermark_offsets(tp0, 10)
        start = max(lo, hi - limit)
        c.assign([tp0])
        c.poll(0.1)
        c.seek(TopicPartition(name, p0, offset=start))
        deadline = time() + 20
        while len(collected) < limit and time() < deadline:
            msg = c.poll(0.4)
            if msg is None:
                continue
            if msg.error():
                if msg.error().code() != KafkaError._PARTITION_EOF:
                    return jsonify(error=str(msg.error())), 500
                break
            val = None
            if msg.value() is not None:
                try:
                    val = msg.value().decode("utf-8", "replace")
                except Exception:
                    val = repr(msg.value())
            collected.append(
                {
                    "partition": int(msg.partition()),
                    "offset": int(msg.offset()),
                    "key": (msg.key() or b"").decode("utf-8", "replace") if msg.key() is not None else None,
                    "value": val,
                }
            )
    finally:
        c.close()
    return jsonify(topic=name, count=len(collected), messages=collected), 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, threaded=True)
PY

log "Installing Kafka admin shim systemd service"
cat >/etc/systemd/system/kafka-admin.service <<'UNIT'
[Unit]
Description=Kafka admin Flask shim
After=kafka.service network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=KAFKA_BOOTSTRAP=localhost:9092
ExecStart=/usr/bin/python3 /opt/kafka/kafka_admin.py
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now kafka-admin.service
log "Kafka + admin shim user-data completed successfully"
